spring:
  application:
    name: auth
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000
          quitwait: false
    servlet:
      multipart:
        max-file-size: 20MB
        max-request-size: 20MB


  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${POSTGRES_DB}?client_encoding=LATIN1
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

cors:
  allowed-origins: "http://localhost:4200"


jwt:
  secret: "QW1hemluZ0tpZHNKd3RTZWNyZXRBbWF6aW5nS2lkc0p3dFNlY3JldEFtYXppbmdLaWRzSnd0U2VjcmV0"
  issuer: "auth"


app:
  ws:
#    endpoint: http://localhost:4200/#/auth/validar-cliente
    password-recovery-endpoint: http://localhost:4200/#/auth/cambiar-contraseña
